name: charts_common
version: 0.13.0
description: A common library for charting packages.
homepage: https://github.com/google/charts

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  collection: ^1.17.1
  intl: ^0.18.0
  logging: ^1.1.1
  meta: ^1.9.1
  vector_math: ^2.1.4
