name: charts_flutter
version: 0.13.0
description: Material Design charting library for flutter.
homepage: https://github.com/google/charts

environment:
  sdk: '>=2.18.0 <4.0.0'

  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  #charts_common: ^0.12.0
  charts_common:
     path: ../charts_common/
  collection: ^1.17.1
  intl: ^0.18.1
  logging: ^1.1.1
  meta: ^1.9.1


dev_dependencies:
  build_runner: ^2.4.2
