name: charts_flutter
version: 0.13.1
description: Material Design charting library for flutter.
homepage: https://github.com/google/charts

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.2
  intl: ^0.18.0
  logging: ^1.1.1
  meta: ^1.9.1


dev_dependencies:
  build_runner: ^2.4.6

dependency_overrides:
  charts_common:
    git:
      url: https://github.com/kw2019ltd/charts.git
      ref: master
      path: charts_common
